In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/MaskiVal/DataSets/main/cancer_breast.csv", sep = ",")

In [4]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [5]:
df.shape

(569, 33)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [7]:
df.nunique()

id                         569
diagnosis                    2
radius_mean                456
texture_mean               479
perimeter_mean             522
area_mean                  539
smoothness_mean            474
compactness_mean           537
concavity_mean             537
concave points_mean        542
symmetry_mean              432
fractal_dimension_mean     499
radius_se                  540
texture_se                 519
perimeter_se               533
area_se                    528
smoothness_se              547
compactness_se             541
concavity_se               533
concave points_se          507
symmetry_se                498
fractal_dimension_se       545
radius_worst               457
texture_worst              511
perimeter_worst            514
area_worst                 544
smoothness_worst           411
compactness_worst          529
concavity_worst            539
concave points_worst       492
symmetry_worst             500
fractal_dimension_worst    535
Unnamed: 32                  0
dtype: int64

In [8]:
df.isna().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [9]:
df_CduS = df.drop(columns = ["id", "Unnamed: 32"], axis = 1)

In [10]:
df_CduS.shape

(569, 31)

In [11]:
df_CduS.drop_duplicates()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

#Describe

In [12]:
df_CduS.describe()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [13]:
df_CduS.describe(percentiles = np.arange(0, 1, 0.1))

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
0%,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
10%,10.260000,14.078000,65.830000,321.600000,0.079654,0.049700,0.013686,0.011158,0.149580,0.055338,...,11.234000,17.800000,72.178000,384.720000,0.102960,0.093676,0.045652,0.038460,0.226120,0.065792
20%,11.366000,15.656000,73.292000,396.560000,0.084206,0.059638,0.024930,0.017866,0.158760,0.056864,...,12.498000,20.176000,81.402000,475.980000,0.112520,0.125660,0.091974,0.058086,0.243620,0.069654
30%,12.012000,16.840000,77.360000,444.060000,0.087914,0.070390,0.034400,0.022788,0.165080,0.058840,...,13.314000,21.988000,86.328000,544.140000,0.120740,0.161400,0.136880,0.071656,0.256520,0.073462
40%,12.726000,17.912000,81.938000,496.440000,0.091828,0.079530,0.045070,0.027982,0.172000,0.060204,...,14.008000,23.584000,91.304000,599.700000,0.126320,0.184620,0.177180,0.083914,0.269400,0.076852
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
60%,14.058000,19.968000,91.420000,609.740000,0.099338,0.108740,0.086212,0.048318,0.185480,0.063148,...,16.004000,26.724000,105.740000,781.180000,0.137680,0.251400,0.286600,0.121800,0.296480,0.083202
70%,15.056000,21.272000,98.200000,700.660000,0.103260,0.122420,0.111920,0.064496,0.192800,0.065048,...,17.386000,28.460000,115.900000,926.960000,0.142600,0.303960,0.349920,0.150800,0.310220,0.088984
80%,17.068000,22.440000,111.680000,915.060000,0.107500,0.141900,0.149780,0.084254,0.200540,0.067630,...,20.294000,30.908000,133.500000,1269.000000,0.150080,0.367060,0.419540,0.177540,0.325380,0.095934
90%,19.530000,24.992000,129.100000,1177.400000,0.114820,0.175460,0.203040,0.100420,0.214940,0.072266,...,23.682000,33.646000,157.740000,1673.000000,0.161480,0.447840,0.571320,0.208940,0.360080,0.106320
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [14]:
numeric_columns = df_CduS.columns[1:-1]

for c in numeric_columns:
  print(f"Statistiques pour la colonne {c} selon les valeurs de 'diagnosis':\n")
  grouped = df_CduS.groupby("diagnosis")[c].describe(percentiles = np.arange(0, 1, 0.1))
  print(grouped.to_markdown())
  print("\n")

Statistiques pour la colonne radius_mean selon les valeurs de 'diagnosis':

| diagnosis   |   count |    mean |     std |    min |     0% |     10% |    20% |    30% |    40% |    50% |    60% |    70% |    80% |    90% |   max |
|:------------|--------:|--------:|--------:|-------:|-------:|--------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|------:|
| B           |     357 | 12.1465 | 1.78051 |  6.981 |  6.981 |  9.7266 | 10.67  | 11.318 | 11.722 | 12.2   | 12.662 | 13.05  | 13.648 | 14.452 | 17.85 |
| M           |     212 | 17.4628 | 3.20397 | 10.95  | 10.95  | 13.61   | 14.616 | 15.46  | 16.244 | 17.325 | 18.286 | 19.204 | 20.154 | 21.075 | 28.11 |


Statistiques pour la colonne texture_mean selon les valeurs de 'diagnosis':

| diagnosis   |   count |    mean |     std |   min |    0% |    10% |    20% |    30% |    40% |   50% |    60% |    70% |    80% |    90% |   max |
|:------------|--------:|--------:|--------:|------:|------:|-------:|-------:|-------:|-------:|------:|-------:|-------:|-------:|-------:|------:|
| B           |     357 | 17.9148 | 3.99512 |  9.71 |  9.71 | 13.308 | 14.716 | 15.668 | 16.502 | 17.39 | 18.232 | 19.102 | 20.668 | 22.868 | 33.81 |
| M           |     212 | 21.6049 | 3.77947 | 10.38 | 10.38 | 17.252 | 18.776 | 19.785 | 20.536 | 21.46 | 22.032 | 23.102 | 24.438 | 26.452 | 39.28 |


Statistiques pour la colonne perimeter_mean selon les valeurs de 'diagnosis':

| diagnosis   |   count |     mean |     std |   min |    0% |    10% |    20% |     30% |     40% |    50% |     60% |    70% |     80% |     90% |   max |
|:------------|--------:|---------:|--------:|------:|------:|-------:|-------:|--------:|--------:|-------:|--------:|-------:|--------:|--------:|------:|
| B           |     357 |  78.0754 | 11.8074 | 43.79 | 43.79 | 61.584 | 68.65  |  72.706 |  75.346 |  78.18 |  81.362 |  84.14 |  87.872 |  94.174 | 114.6 |
| M           |     212 | 115.365  | 21.8547 | 71.9  | 71.9  | 88.424 | 95.724 | 102.43  | 107.74  | 114.2  | 120.6   | 127.64 | 132.48  | 140.82  | 188.5 |


Statistiques pour la colonne area_mean selon les valeurs de 'diagnosis':

| diagnosis   |   count |    mean |     std |   min |    0% |    10% |    20% |    30% |    40% |   50% |     60% |     70% |    80% |     90% |    max |
|:------------|--------:|--------:|--------:|------:|------:|-------:|-------:|-------:|-------:|------:|--------:|--------:|-------:|--------:|-------:|
| B           |     357 | 462.79  | 134.287 | 143.5 | 143.5 | 288.86 | 347.52 | 394.1  | 421.76 | 458.4 |  492.58 |  525.44 |  572.2 |  644.96 |  992.1 |
| M           |     212 | 978.376 | 367.938 | 361.6 | 361.6 | 573.13 | 659.98 | 733.75 | 814.54 | 932   | 1040.6  | 1150.8  | 1249.4 | 1382    | 2501   |


Statistiques pour la colonne smoothness_mean selon les valeurs de 'diagnosis':

| diagnosis   |   count |      mean |       std |     min |      0% |      10% |      20% |      30% |      40% |     50% |      60% |     70% |     80% |     90% |    max |
|:------------|--------:|----------:|----------:|--------:|--------:|---------:|---------:|---------:|---------:|--------:|---------:|--------:|--------:|--------:|-------:|
| B           |     357 | 0.0924776 | 0.0134461 | 0.05263 | 0.05263 | 0.077122 | 0.081182 | 0.084704 | 0.087594 | 0.09076 | 0.095208 | 0.09908 | 0.10326 | 0.10884 | 0.1634 |
| M           |     212 | 0.102898  | 0.0126082 | 0.07371 | 0.07371 | 0.087803 | 0.091744 | 0.094964 | 0.098728 | 0.1022  | 0.10514  | 0.10887 | 0.11386 | 0.11825 | 0.1447 |


Statistiques pour la colonne compactness_mean selon les valeurs de 'diagnosis':

| diagnosis   |   count |      mean |       std |     min |      0% |      10% |      20% |      30% |      40% |     50% |      60% |      70% |     80% |     90% |    max |
|:------------|--------:|----------:|----------:|--------:|--------:|---------:|---------:|---------:|---------:|--------:|---------:|---------:|--------:|--------:|-------:|
| B           |     357 | 0.0800846 | 0.03375   | 0.01938 | 0.01938 | 0.042916 | 0.052412 | 0.059534 | 0.066902 | 0.07529 | 0.081254 | 0.091708 | 0.1068  | 0.1227  | 0.2239 |
| M           |     212 | 0.145188  | 0.0539875 | 0.04605 | 0.04605 | 0.084284 | 0.1037   | 0.11436  | 0.12694  | 0.13235 | 0.15078  | 0.16478  | 0.18642 | 0.21532 | 0.3454 |


Statistiques pour la colonne concavity_mean selon les valeurs de 'diagnosis':

| diagnosis   |   count |      mean |       std |     min |      0% |      10% |      20% |      30% |      40% |     50% |      60% |      70% |      80% |      90% |    max |
|:------------|--------:|----------:|----------:|--------:|--------:|---------:|---------:|---------:|---------:|--------:|---------:|---------:|---------:|---------:|-------:|
| B           |     357 | 0.0460576 | 0.0434422 | 0       | 0       | 0.007406 | 0.017216 | 0.023662 | 0.029792 | 0.03709 | 0.043352 | 0.054052 | 0.067348 | 0.092564 | 0.4108 |
| M           |     212 | 0.160775  | 0.0750193 | 0.02398 | 0.02398 | 0.080349 | 0.099412 | 0.11488  | 0.13402  | 0.15135 | 0.16826  | 0.19043  | 0.21346  | 0.25059  | 0.4268 |


Statistiques pour la colonne concave points_mean selon les valeurs de 'diagnosis':

| diagnosis   |   count |      mean |       std |     min |      0% |       10% |      20% |      30% |      40% |     50% |      60% |      70% |      80% |      90% |     max |
|:------------|--------:|----------:|----------:|--------:|--------:|----------:|---------:|---------:|---------:|--------:|---------:|---------:|---------:|---------:|--------:|
| B           |     357 | 0.0257174 | 0.0159088 | 0       | 0       | 0.0069828 | 0.012946 | 0.017684 | 0.020364 | 0.02344 | 0.02736  | 0.030078 | 0.037088 | 0.048024 | 0.08534 |
| M           |     212 | 0.08799   | 0.0343739 | 0.02031 | 0.02031 | 0.051947  | 0.05981  | 0.066743 | 0.079464 | 0.08628 | 0.090428 | 0.097313 | 0.11018  | 0.13715  | 0.2012  |


Statistiques pour la colonne symmetry_mean selon les valeurs de 'diagnosis':

| diagnosis   |   count |     mean |       std |    min |     0% |     10% |     20% |     30% |     40% |    50% |     60% |     70% |     80% |     90% |    max |
|:------------|--------:|---------:|----------:|-------:|-------:|--------:|--------:|--------:|--------:|-------:|--------:|--------:|--------:|--------:|-------:|
| B           |     357 | 0.174186 | 0.0248068 | 0.106  | 0.106  | 0.1454  | 0.1539  | 0.16118 | 0.16652 | 0.1714 | 0.17828 | 0.18566 | 0.19332 | 0.2027  | 0.2743 |
| M           |     212 | 0.192909 | 0.0276381 | 0.1308 | 0.1308 | 0.15904 | 0.17176 | 0.17826 | 0.18328 | 0.1899 | 0.1953  | 0.20666 | 0.21306 | 0.22519 | 0.304  |


Statistiques pour la colonne fractal_dimension_mean selon les valeurs de 'diagnosis':

| diagnosis   |   count |      mean |        std |     min |      0% |      10% |      20% |      30% |      40% |      50% |      60% |      70% |      80% |      90% |     max |
|:------------|--------:|----------:|-----------:|--------:|--------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|--------:|
| B           |     357 | 0.0628674 | 0.00674734 | 0.05185 | 0.05185 | 0.055958 | 0.057508 | 0.058978 | 0.060292 | 0.06154  | 0.063188 | 0.06472  | 0.066754 | 0.070812 | 0.09575 |
| M           |     212 | 0.0626801 | 0.00757332 | 0.04996 | 0.04996 | 0.054196 | 0.05588  | 0.057504 | 0.06008  | 0.061575 | 0.063066 | 0.065744 | 0.06877  | 0.073677 | 0.09744 |


Statistiques pour la colonne radius_se selon les valeurs de 'diagnosis':

| diagnosis   |   count |     mean |      std |    min |     0% |     10% |     20% |     30% |     40% |    50% |     60% |     70% |     80% |     90% |    max |
|:------------|--------:|---------:|---------:|-------:|-------:|--------:|--------:|--------:|--------:|-------:|--------:|--------:|--------:|--------:|-------:|
| B           |     357 | 0.284082 | 0.11257  | 0.1115 | 0.1115 | 0.16908 | 0.19136 | 0.21934 | 0.23778 | 0.2575 | 0.28842 | 0.32744 | 0.3598  | 0.42092 | 0.8811 |
| M           |     212 | 0.609083 | 0.345039 | 0.1938 | 0.1938 | 0.27879 | 0.33502 | 0.42033 | 0.46768 | 0.5472 | 0.60678 | 0.70243 | 0.82838 | 1.0036  | 2.873  |


Statistiques pour la colonne texture_se selon les valeurs de 'diagnosis':

| diagnosis   |   count |    mean |      std |    min |     0% |     10% |     20% |     30% |     40% |    50% |    60% |    70% |    80% |    90% |   max |
|:------------|--------:|--------:|---------:|-------:|-------:|--------:|--------:|--------:|--------:|-------:|-------:|-------:|-------:|-------:|------:|
| B           |     357 | 1.22038 | 0.58918  | 0.3602 | 0.3602 | 0.61016 | 0.74114 | 0.87144 | 0.99146 | 1.108  | 1.2482 | 1.412  | 1.6002 | 1.9244 | 4.885 |
| M           |     212 | 1.21091 | 0.483178 | 0.3621 | 0.3621 | 0.70087 | 0.83538 | 0.92401 | 1.0178  | 1.1025 | 1.2152 | 1.3583 | 1.501  | 1.8414 | 3.568 |


Statistiques pour la colonne perimeter_se selon les valeurs de 'diagnosis':

| diagnosis   |   count |    mean |      std |   min |    0% |    10% |    20% |    30% |    40% |    50% |    60% |   70% |    80% |    90% |    max |
|:------------|--------:|--------:|---------:|------:|------:|-------:|-------:|-------:|-------:|-------:|-------:|------:|-------:|-------:|-------:|
| B           |     357 | 2.00032 | 0.771169 | 0.757 | 0.757 | 1.1706 | 1.3566 | 1.5076 | 1.6604 | 1.851  | 2.072  | 2.28  | 2.5596 | 3.0234 |  5.118 |
| M           |     212 | 4.32393 | 2.56855  | 1.334 | 1.334 | 2.0624 | 2.4644 | 2.9063 | 3.186  | 3.6795 | 4.1676 | 4.789 | 5.744  | 7.3309 | 21.98  |


Statistiques pour la colonne area_se selon les valeurs de 'diagnosis':

| diagnosis   |   count |    mean |      std |    min |     0% |    10% |    20% |    30% |    40% |    50% |    60% |    70% |     80% |     90% |    max |
|:------------|--------:|--------:|---------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|--------:|--------:|-------:|
| B           |     357 | 21.1351 |  8.84347 |  6.802 |  6.802 | 11.824 | 14.168 | 16.406 | 17.954 | 19.63  | 21.01  | 23.294 |  27.078 |  31.192 |  77.11 |
| M           |     212 | 72.6724 | 61.3553  | 13.99  | 13.99  | 24.257 | 32.642 | 40.805 | 48.406 | 58.455 | 69.578 | 86.885 | 102.38  | 128.27  | 542.2  |


Statistiques pour la colonne smoothness_se selon les valeurs de 'diagnosis':

| diagnosis   |   count |       mean |        std |      min |       0% |       10% |       20% |       30% |       40% |       50% |       60% |       70% |       80% |       90% |     max |
|:------------|--------:|-----------:|-----------:|---------:|---------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|--------:|
| B           |     357 | 0.0071959  | 0.00306061 | 0.001713 | 0.001713 | 0.0041414 | 0.004869  | 0.0054198 | 0.005884  | 0.00653   | 0.0072016 | 0.007841  | 0.009102  | 0.01104   | 0.02177 |
| M           |     212 | 0.00678009 | 0.00289043 | 0.002667 | 0.002667 | 0.0044296 | 0.0048836 | 0.0054179 | 0.0057594 | 0.0062095 | 0.0066504 | 0.0074708 | 0.0081576 | 0.0095249 | 0.03113 |


Statistiques pour la colonne compactness_se selon les valeurs de 'diagnosis':

| diagnosis   |   count |      mean |       std |      min |       0% |       10% |      20% |      30% |      40% |     50% |      60% |      70% |      80% |      90% |    max |
|:------------|--------:|----------:|----------:|---------:|---------:|----------:|---------:|---------:|---------:|--------:|---------:|---------:|---------:|---------:|-------:|
| B           |     357 | 0.0214382 | 0.0163515 | 0.002252 | 0.002252 | 0.0081728 | 0.010414 | 0.012266 | 0.01397  | 0.01631 | 0.018818 | 0.022946 | 0.03049  | 0.041412 | 0.1064 |
| M           |     212 | 0.0322812 | 0.0183872 | 0.008422 | 0.008422 | 0.013851  | 0.018084 | 0.022078 | 0.025398 | 0.02859 | 0.031934 | 0.037064 | 0.042114 | 0.054604 | 0.1354 |


Statistiques pour la colonne concavity_se selon les valeurs de 'diagnosis':

| diagnosis   |   count |      mean |       std |     min |      0% |       10% |      20% |      30% |      40% |      50% |      60% |      70% |      80% |      90% |    max |
|:------------|--------:|----------:|----------:|--------:|--------:|----------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|-------:|
| B           |     357 | 0.0259967 | 0.0329182 | 0       | 0       | 0.0052864 | 0.009402 | 0.01281  | 0.01553  | 0.0184   | 0.020914 | 0.027052 | 0.034506 | 0.049878 | 0.396  |
| M           |     212 | 0.041824  | 0.0216034 | 0.01101 | 0.01101 | 0.020528  | 0.025766 | 0.028652 | 0.033294 | 0.037125 | 0.04244  | 0.047264 | 0.054858 | 0.067791 | 0.1438 |


Statistiques pour la colonne concave points_se selon les valeurs de 'diagnosis':

| diagnosis   |   count |       mean |        std |      min |       0% |       10% |       20% |       30% |       40% |      50% |      60% |      70% |      80% |      90% |     max |
|:------------|--------:|-----------:|-----------:|---------:|---------:|----------:|----------:|----------:|----------:|---------:|---------:|---------:|---------:|---------:|--------:|
| B           |     357 | 0.00985765 | 0.00570862 | 0        | 0        | 0.0047552 | 0.0060544 | 0.0068952 | 0.0080152 | 0.009061 | 0.01011  | 0.011334 | 0.012954 | 0.015922 | 0.05279 |
| M           |     212 | 0.0150605  | 0.00551736 | 0.005174 | 0.005174 | 0.0092359 | 0.010844  | 0.012027  | 0.013018  | 0.014205 | 0.015312 | 0.016654 | 0.01843  | 0.021553 | 0.0409  |


Statistiques pour la colonne symmetry_se selon les valeurs de 'diagnosis':

| diagnosis   |   count |      mean |        std |      min |       0% |      10% |      20% |      30% |      40% |     50% |      60% |      70% |      80% |      90% |     max |
|:------------|--------:|----------:|-----------:|---------:|---------:|---------:|---------:|---------:|---------:|--------:|---------:|---------:|---------:|---------:|--------:|
| B           |     357 | 0.0205838 | 0.00699854 | 0.009539 | 0.009539 | 0.013274 | 0.014884 | 0.016168 | 0.017984 | 0.01909 | 0.020454 | 0.022584 | 0.02597  | 0.03004  | 0.06146 |
| M           |     212 | 0.0204724 | 0.0100649  | 0.007882 | 0.007882 | 0.012642 | 0.013996 | 0.015047 | 0.016194 | 0.0177  | 0.019336 | 0.021155 | 0.023974 | 0.030507 | 0.07895 |


Statistiques pour la colonne fractal_dimension_se selon les valeurs de 'diagnosis':

| diagnosis   |   count |       mean |        std |       min |        0% |       10% |       20% |       30% |       40% |       50% |       60% |       70% |       80% |       90% |     max |
|:------------|--------:|-----------:|-----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|--------:|
| B           |     357 | 0.00363605 | 0.00293822 | 0.0008948 | 0.0008948 | 0.0016488 | 0.0019562 | 0.002221  | 0.0024888 | 0.002808  | 0.0033216 | 0.00377   | 0.0046228 | 0.0060474 | 0.02984 |
| M           |     212 | 0.00406241 | 0.0020415  | 0.001087  | 0.001087  | 0.0019102 | 0.0024684 | 0.0028535 | 0.0033174 | 0.0037395 | 0.0040988 | 0.0045594 | 0.0052406 | 0.0061924 | 0.01284 |


Statistiques pour la colonne radius_worst selon les valeurs de 'diagnosis':

| diagnosis   |   count |    mean |     std |   min |    0% |    10% |    20% |   30% |    40% |   50% |    60% |    70% |    80% |    90% |   max |
|:------------|--------:|--------:|--------:|------:|------:|-------:|-------:|------:|-------:|------:|-------:|-------:|-------:|-------:|------:|
| B           |     357 | 13.3798 | 1.98137 |  7.93 |  7.93 | 10.756 | 11.664 | 12.4  | 13.038 | 13.35 | 13.812 | 14.402 | 15.05  | 16.05  | 19.82 |
| M           |     212 | 21.1348 | 4.28357 | 12.84 | 12.84 | 16.017 | 17.27  | 18.26 | 19.782 | 20.59 | 22.03  | 23.212 | 24.326 | 26.221 | 36.04 |


Statistiques pour la colonne texture_worst selon les valeurs de 'diagnosis':

| diagnosis   |   count |    mean |     std |   min |    0% |    10% |    20% |    30% |    40% |    50% |    60% |    70% |    80% |    90% |   max |
|:------------|--------:|--------:|--------:|------:|------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|-------:|------:|
| B           |     357 | 23.5151 | 5.49395 | 12.02 | 12.02 | 16.936 | 18.99  | 20.208 | 21.574 | 22.82  | 24.376 | 25.726 | 27.86  | 31.366 | 41.78 |
| M           |     212 | 29.3182 | 5.4348  | 16.67 | 16.67 | 23.062 | 25.094 | 26.363 | 27.668 | 28.945 | 30.518 | 31.677 | 33.386 | 35.577 | 49.54 |


Statistiques pour la colonne perimeter_worst selon les valeurs de 'diagnosis':

| diagnosis   |   count |     mean |     std |   min |    0% |    10% |     20% |    30% |    40% |    50% |     60% |    70% |     80% |    90% |   max |
|:------------|--------:|---------:|--------:|------:|------:|-------:|--------:|-------:|-------:|-------:|--------:|-------:|--------:|-------:|------:|
| B           |     357 |  87.0059 | 13.5271 | 50.41 | 50.41 |  69.08 |  75.392 |  80.61 |  84.13 |  86.92 |  89.658 |  94.18 |  98.394 | 104.5  | 127.1 |
| M           |     212 | 141.37   | 29.4571 | 85.1  | 85.1  | 107.32 | 115.14  | 123.59 | 129.24 | 138    | 145.84  | 153.11 | 162.62  | 179.05 | 251.2 |


Statistiques pour la colonne area_worst selon les valeurs de 'diagnosis':

| diagnosis   |   count |     mean |     std |   min |    0% |    10% |    20% |    30% |    40% |    50% |     60% |     70% |     80% |     90% |   max |
|:------------|--------:|---------:|--------:|------:|------:|-------:|-------:|-------:|-------:|-------:|--------:|--------:|--------:|--------:|------:|
| B           |     357 |  558.899 | 163.601 | 185.2 | 185.2 | 354.56 | 411.34 |  472.2 |  516.1 |  547.4 |  586.36 |  633.02 |  697.84 |  779.34 |  1210 |
| M           |     212 | 1422.29  | 597.968 | 508.1 | 508.1 | 787.91 | 907.64 | 1026.5 | 1219.6 | 1303   | 1482.6  | 1647.4  | 1817.8  | 2088.2  |  4254 |


Statistiques pour la colonne smoothness_worst selon les valeurs de 'diagnosis':

| diagnosis   |   count |     mean |       std |     min |      0% |      10% |     20% |     30% |     40% |     50% |     60% |     70% |     80% |     90% |    max |
|:------------|--------:|---------:|----------:|--------:|--------:|---------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|-------:|
| B           |     357 | 0.124959 | 0.0200135 | 0.07117 | 0.07117 | 0.099652 | 0.10736 | 0.11384 | 0.12064 | 0.1254  | 0.1297  | 0.1347  | 0.14116 | 0.1496  | 0.2006 |
| M           |     212 | 0.144845 | 0.0218698 | 0.08822 | 0.08822 | 0.11819  | 0.12582 | 0.13488 | 0.1401  | 0.14345 | 0.14916 | 0.15307 | 0.16202 | 0.17298 | 0.2226 |


Statistiques pour la colonne compactness_worst selon les valeurs de 'diagnosis':

| diagnosis   |   count |     mean |      std |     min |      0% |      10% |     20% |     30% |     40% |     50% |     60% |     70% |     80% |     90% |    max |
|:------------|--------:|---------:|---------:|--------:|--------:|---------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|-------:|
| B           |     357 | 0.182673 | 0.09218  | 0.02729 | 0.02729 | 0.077494 | 0.10204 | 0.12544 | 0.15064 | 0.1698  | 0.1879  | 0.21598 | 0.25046 | 0.30532 | 0.5849 |
| M           |     212 | 0.374824 | 0.170372 | 0.05131 | 0.05131 | 0.19259  | 0.22922 | 0.27414 | 0.3141  | 0.35635 | 0.39036 | 0.42184 | 0.4773  | 0.59523 | 1.058  |


Statistiques pour la colonne concavity_worst selon les valeurs de 'diagnosis':

| diagnosis   |   count |     mean |      std |     min |      0% |     10% |      20% |      30% |     40% |    50% |     60% |     70% |     80% |    90% |   max |
|:------------|--------:|---------:|---------:|--------:|--------:|--------:|---------:|---------:|--------:|-------:|--------:|--------:|--------:|-------:|------:|

Le client nous a informé qu'il y avait des valeurs à 0 pour les marqueurs "concavity" et souhaite que nous supprimions les lignes dans lesquelles ils apparaissent

Nous allons commencer par les identifier puis nous les supprimerons

In [15]:
# identification des lignes avec des valeurs 0 pour les marqueurs "concavity"

condition = (df['concavity_mean'] == 0) | (df['concavity_se'] == 0) | (df['concavity_worst'] == 0)
rows_with_zeros = df[condition]

print(rows_with_zeros)

          id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
101   862722         B        6.981         13.43           43.79      143.5
140   868999         B        9.738         11.97           61.24      288.5
174   871642         B       10.660         15.15           67.49      349.6
175   872113         B        8.671         14.45           54.42      227.2
192   875099         B        9.720         18.22           60.73      288.1
314   894047         B        8.597         18.60           54.09      221.2
391   903483         B        8.734         16.84           55.27      234.3
473  9113846         B       12.270         29.97           77.42      465.4
538   921092         B        7.729         25.49           47.98      178.8
550   923748         B       10.860         21.48           68.51      360.5
557   925236         B        9.423         27.88           59.26      271.3
561   925311         B       11.200         29.37           70.67      386.0
568    92751         B        7.760         24.54           47.92      181.0

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
101          0.11700           0.07568             0.0                  0.0
140          0.09250           0.04102             0.0                  0.0
174          0.08792           0.04302             0.0                  0.0
175          0.09138           0.04276             0.0                  0.0
192          0.06950           0.02344             0.0                  0.0
314          0.10740           0.05847             0.0                  0.0
391          0.10390           0.07428             0.0                  0.0
473          0.07699           0.03398             0.0                  0.0
538          0.08098           0.04878             0.0                  0.0
550          0.07431           0.04227             0.0                  0.0
557          0.08123           0.04971             0.0                  0.0
561          0.07449           0.03558             0.0                  0.0
568          0.05263           0.04362             0.0                  0.0

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
101  ...          19.54            50.41       185.2           0.15840
140  ...          14.10            66.53       342.9           0.12340
174  ...          19.20            73.20       408.3           0.10760
175  ...          17.04            58.36       259.2           0.11620
192  ...          20.83            62.25       303.8           0.07117
314  ...          22.44            56.65       240.1           0.13470
391  ...          22.80            64.01       317.0           0.14600
473  ...          38.05            85.08       558.9           0.09422
538  ...          30.92            57.17       248.0           0.12560
550  ...          24.77            74.08       412.3           0.10010
557  ...          34.24            66.50       330.6           0.10730
561  ...          38.30            75.19       439.6           0.09267
568  ...          30.37            59.16       268.6           0.08996

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
101            0.12020              0.0                   0.0          0.2932
140            0.07204              0.0                   0.0          0.3105
174            0.06791              0.0                   0.0          0.2710
175            0.07057              0.0                   0.0          0.2592
192            0.02729              0.0                   0.0          0.1909
314            0.07767              0.0                   0.0          0.3142
391            0.13100              0.0                   0.0          0.2445
473            0.05213              0.0                   0.0          0.2409
538            0.08340              0.0                   0.0          0.3058
550            0.07348              0.0                   0.0          0.2458
557            0.07158              0.0                   0.0          0.2475
561            0.05494              0.0                   0.0          0.1566
568            0.06444              0.0                   0.0          0.2871

     fractal_dimension_worst  Unnamed: 32
101                  0.09382          NaN
140                  0.08151          NaN
174                  0.06164          NaN
175                  0.07848          NaN
192                  0.06559          NaN
314                  0.08116          NaN
391                  0.08865          NaN
473                  0.06743          NaN
538                  0.09938          NaN
550                  0.06592          NaN
557                  0.06969          NaN
561                  0.05905          NaN
568                  0.07039          NaN

[13 rows x 33 columns]

In [16]:
# suppression des lignes

df_CduS = df_CduS[(df_CduS["concavity_mean"] != 0) & (df_CduS["concavity_se"] != 0) & (df_CduS["concavity_worst"] != 0)]

In [17]:
df_CduS.shape

(556, 31)

#Outliers

In [18]:
print(df_CduS.head().to_markdown())

|    | diagnosis   |   radius_mean |   texture_mean |   perimeter_mean |   area_mean |   smoothness_mean |   compactness_mean |   concavity_mean |   concave points_mean |   symmetry_mean |   fractal_dimension_mean |   radius_se |   texture_se |   perimeter_se |   area_se |   smoothness_se |   compactness_se |   concavity_se |   concave points_se |   symmetry_se |   fractal_dimension_se |   radius_worst |   texture_worst |   perimeter_worst |   area_worst |   smoothness_worst |   compactness_worst |   concavity_worst |   concave points_worst |   symmetry_worst |   fractal_dimension_worst |
|---:|:------------|--------------:|---------------:|-----------------:|------------:|------------------:|-------------------:|-----------------:|----------------------:|----------------:|-------------------------:|------------:|-------------:|---------------:|----------:|----------------:|-----------------:|---------------:|--------------------:|--------------:|-----------------------:|---------------:|----------------:|------------------:|-------------:|-------------------:|--------------------:|------------------:|-----------------------:|-----------------:|--------------------------:|
|  0 | M           |         17.99 |          10.38 |           122.8  |      1001   |           0.1184  |            0.2776  |           0.3001 |               0.1471  |          0.2419 |                  0.07871 |      1.095  |       0.9053 |          8.589 |    153.4  |        0.006399 |          0.04904 |        0.05373 |             0.01587 |       0.03003 |               0.006193 |          25.38 |           17.33 |            184.6  |       2019   |             0.1622 |              0.6656 |            0.7119 |                 0.2654 |           0.4601 |                   0.1189  |
|  1 | M           |         20.57 |          17.77 |           132.9  |      1326   |           0.08474 |            0.07864 |           0.0869 |               0.07017 |          0.1812 |                  0.05667 |      0.5435 |       0.7339 |          3.398 |     74.08 |        0.005225 |          0.01308 |        0.0186  |             0.0134  |       0.01389 |               0.003532 |          24.99 |           23.41 |            158.8  |       1956   |             0.1238 |              0.1866 |            0.2416 |                 0.186  |           0.275  |                   0.08902 |
|  2 | M           |         19.69 |          21.25 |           130    |      1203   |           0.1096  |            0.1599  |           0.1974 |               0.1279  |          0.2069 |                  0.05999 |      0.7456 |       0.7869 |          4.585 |     94.03 |        0.00615  |          0.04006 |        0.03832 |             0.02058 |       0.0225  |               0.004571 |          23.57 |           25.53 |            152.5  |       1709   |             0.1444 |              0.4245 |            0.4504 |                 0.243  |           0.3613 |                   0.08758 |
|  3 | M           |         11.42 |          20.38 |            77.58 |       386.1 |           0.1425  |            0.2839  |           0.2414 |               0.1052  |          0.2597 |                  0.09744 |      0.4956 |       1.156  |          3.445 |     27.23 |        0.00911  |          0.07458 |        0.05661 |             0.01867 |       0.05963 |               0.009208 |          14.91 |           26.5  |             98.87 |        567.7 |             0.2098 |              0.8663 |            0.6869 |                 0.2575 |           0.6638 |                   0.173   |
|  4 | M           |         20.29 |          14.34 |           135.1  |      1297   |           0.1003  |            0.1328  |           0.198  |               0.1043  |          0.1809 |                  0.05883 |      0.7572 |       0.7813 |          5.438 |     94.44 |        0.01149  |          0.02461 |        0.05688 |             0.01885 |       0.01756 |               0.005115 |          22.54 |           16.67 |            152.2  |       1575   |             0.1374 |              0.205  |            0.4    |                 0.1625 |           0.2364 |                   0.07678 |

In [19]:
# Séparer les données en fonction des étiquettes
df_benign = df_CduS[df_CduS['diagnosis'] == "B"]
df_malignant = df_CduS[df_CduS['diagnosis'] == "M"]

B_numeric = df_benign.select_dtypes(include = "number")
M_numeric = df_malignant.select_dtypes(include = "number")

##Outliers Cas Bénins

In [20]:
# Détection des outliers pour les cas bénins
Q1_benign = B_numeric.quantile(0.25)
Q3_benign = M_numeric.quantile(0.75)
IQR_benign = Q3_benign - Q1_benign
lower_bound_benign = Q1_benign - 1.5 * IQR_benign
upper_bound_benign = Q3_benign + 1.5 * IQR_benign
outliers_benign = ((B_numeric < lower_bound_benign) | (B_numeric > upper_bound_benign)).any(axis=1)
outliers_df_benign = B_numeric[outliers_benign]

In [21]:
print("Outliers dans les cas bénins:")
print(outliers_df_benign.to_markdown())

Outliers dans les cas bénins:
|     |   radius_mean |   texture_mean |   perimeter_mean |   area_mean |   smoothness_mean |   compactness_mean |   concavity_mean |   concave points_mean |   symmetry_mean |   fractal_dimension_mean |   radius_se |   texture_se |   perimeter_se |   area_se |   smoothness_se |   compactness_se |   concavity_se |   concave points_se |   symmetry_se |   fractal_dimension_se |   radius_worst |   texture_worst |   perimeter_worst |   area_worst |   smoothness_worst |   compactness_worst |   concavity_worst |   concave points_worst |   symmetry_worst |   fractal_dimension_worst |
|----:|--------------:|---------------:|-----------------:|------------:|------------------:|-------------------:|-----------------:|----------------------:|----------------:|-------------------------:|------------:|-------------:|---------------:|----------:|----------------:|-----------------:|---------------:|--------------------:|--------------:|-----------------------:|---------------:|----------------:|------------------:|-------------:|-------------------:|--------------------:|------------------:|-----------------------:|-----------------:|--------------------------:|
|  60 |        10.17  |          14.88 |            64.55 |       311.9 |           0.1134  |            0.08061 |         0.01084  |              0.0129   |          0.2743 |                  0.0696  |      0.5158 |       1.441  |          3.312 |    34.62  |        0.007514 |          0.01099 |       0.007665 |            0.008193 |       0.04183 |               0.005953 |         11.02  |           17.45 |             69.86 |        368.6 |            0.1275  |             0.09866 |           0.02168 |                0.02579 |           0.3557 |                   0.0802  |
|  61 |         8.598 |          20.98 |            54.66 |       221.8 |           0.1243  |            0.08963 |         0.03     |              0.009259 |          0.1828 |                  0.06757 |      0.3582 |       2.067  |          2.493 |    18.39  |        0.01193  |          0.03162 |       0.03     |            0.009259 |       0.03357 |               0.003048 |          9.565 |           27.04 |             62.06 |        273.9 |            0.1639  |             0.1698  |           0.09001 |                0.02778 |           0.2972 |                   0.07712 |
|  63 |         9.173 |          13.86 |            59.2  |       260.9 |           0.07721 |            0.08751 |         0.05988  |              0.0218   |          0.2341 |                  0.06963 |      0.4098 |       2.265  |          2.608 |    23.52  |        0.008738 |          0.03938 |       0.04312  |            0.0156   |       0.04192 |               0.005822 |         10.01  |           19.23 |             65.59 |        310.1 |            0.09836 |             0.1678  |           0.1397  |                0.05087 |           0.3282 |                   0.0849  |
|  68 |         9.029 |          17.33 |            58.79 |       250.5 |           0.1066  |            0.1413  |         0.313    |              0.04375  |          0.2111 |                  0.08046 |      0.3274 |       1.194  |          1.885 |    17.67  |        0.009549 |          0.08606 |       0.3038   |            0.03322  |       0.04197 |               0.009559 |         10.31  |           22.65 |             65.5  |        324.7 |            0.1482  |             0.4365  |           1.252   |                0.175   |           0.4228 |                   0.1175  |
|  71 |         8.888 |          14.64 |            58.79 |       244   |           0.09783 |            0.1531  |         0.08606  |              0.02872  |          0.1902 |                  0.0898  |      0.5262 |       0.8522 |          3.168 |    25.44  |        0.01721  |          0.09368 |       0.05671  |            0.01766  |       0.02541 |               0.02193  |          9.733 |           15.67 |             62.56 |        284.4 |            0.1207  |             0.2436  |           0.1434  |                0.04786 |           0.2254 |                   0.1084  |
|  76 |        13.53  |          10.94 |            87.91 |       559.2 |           0.1291  |            0.1047  |         0.06877  |              0.06556  |          0.2403 |                  0.06641 |      0.4101 |       1.014  |          2.652 |    32.65  |        0.0134   |          0.02839 |       0.01162  |            0.008239 |       0.02572 |               0.006164 |         14.08  |           12.49 |             91.36 |        605.5 |            0.1451  |             0.1379  |           0.08539 |                0.07407 |           0.271  |                   0.07191 |
| 110 |         9.777 |          16.99 |            62.5  |       290.2 |           0.1037  |            0.08404 |         0.04334  |              0.01778  |          0.1584 |                  0.07065 |      0.403  |       1.424  |          2.747 |    22.87  |        0.01385  |          0.02932 |       0.02722  |            0.01023  |       0.03281 |               0.004638 |         11.05  |           21.47 |             71.68 |        367   |            0.1467  |             0.1765  |           0.13    |                0.05334 |           0.2533 |                   0.08468 |
| 111 |        12.63  |          20.76 |            82.15 |       480.4 |           0.09933 |            0.1209  |         0.1065   |              0.06021  |          0.1735 |                  0.0707  |      0.3424 |       1.803  |          2.711 |    20.48  |        0.01291  |          0.04042 |       0.05101  |            0.02295  |       0.02144 |               0.005891 |         13.33  |           25.47 |             89    |        527.4 |            0.1287  |             0.225   |           0.2216  |                0.1105  |           0.2226 |                   0.08486 |
| 112 |        14.26  |          19.65 |            97.83 |       629.9 |           0.07837 |            0.2233  |         0.3003   |              0.07798  |          0.1704 |                  0.07769 |      0.3628 |       1.49   |          3.399 |    29.25  |        0.005298 |          0.07446 |       0.1435   |            0.02292  |       0.02566 |               0.01298  |         15.3   |           23.73 |            107    |        709   |            0.08949 |             0.4193  |           0.6783  |                0.1505  |           0.2398 |                   0.1082  |
| 116 |         8.95  |          15.76 |            58.74 |       245.2 |           0.09462 |            0.1243  |         0.09263  |              0.02308  |          0.1305 |                  0.07163 |      0.3132 |       0.9789 |          3.28  |    16.94  |        0.01835  |          0.0676  |       0.09263  |            0.02308  |       0.02384 |               0.005601 |          9.414 |           17.07 |             63.34 |        270   |            0.1179  |             0.1879  |           0.1544  |                0.03846 |           0.1652 |                   0.07722 |
| 136 |        11.71  |          16.67 |            74.72 |       423.6 |           0.1051  |            0.06095 |         0.03592  |              0.026    |          0.1339 |                  0.05945 |      0.4489 |       2.508  |          3.258 |    34.37  |        0.006578 |          0.0138  |       0.02662  |            0.01307  |       0.01359 |               0.003707 |         13.33  |           25.48 |             86.16 |        546.7 |            0.1271  |             0.1028  |           0.1046  |                0.06968 |           0.1712 |                   0.07343 |
| 145 |        11.9   |          14.65 |            78.11 |       432.8 |           0.1152  |            0.1296  |         0.0371   |              0.03003  |          0.1995 |                  0.07839 |      0.3962 |       0.6538 |          3.021 |    25.03  |        0.01017  |          0.04741 |       0.02789  |            0.0111   |       0.03127 |               0.009423 |         13.15  |           16.51 |             86.26 |        509.6 |            0.1424  |             0.2517  |           0.0942  |                0.06042 |           0.2727 |                   0.1036  |
| 147 |        14.95  |          18.77 |            97.84 |       689.5 |           0.08138 |            0.1167  |         0.0905   |              0.03562  |          0.1744 |                  0.06493 |      0.422  |       1.909  |          3.271 |    39.43  |        0.00579  |          0.04877 |       0.05303  |            0.01527  |       0.03356 |               0.009368 |         16.25  |           25.47 |            107.1  |        809.7 |            0.0997  |             0.2521  |           0.25    |                0.08405 |           0.2852 |                   0.09218 |
| 151 |         8.219 |          20.7  |            53.27 |       203.9 |           0.09405 |            0.1305  |         0.1321   |              0.02168  |          0.2222 |                  0.08261 |      0.1935 |       1.962  |          1.243 |    10.21  |        0.01243  |          0.05416 |       0.07753  |            0.01022  |       0.02309 |               0.01178  |          9.092 |           29.72 |             58.08 |        249.8 |            0.163   |             0.431   |           0.5381  |                0.07879 |           0.3322 |                   0.1486  |
| 152 |         9.731 |          15.34 |            63.78 |       300.2 |           0.1072  |            0.1599  |         0.4108   |              0.07857  |          0.2548 |                  0.09296 |      0.8245 |       2.664  |          4.073 |    49.85  |        0.01097  |          0.09586 |       0.396    |            0.05279  |       0.03546 |               0.02984  |         11.02  |           19.49 |             71.04 |        380.5 |            0.1292  |             0.2772  |           0.8216  |                0.1571  |           0.3108 |                   0.1259  |
| 160 |        11.75  |          20.18 |            76.1  |       419.8 |           0.1089  |            0.1141  |         0.06843  |              0.03738  |          0.1993 |                  0.06453 |      0.5018 |       1.693  |          3.926 |    38.34  |        0.009433 |          0.02405 |       0.04167  |            0.01152  |       0.03397 |               0.005061 |         13.32  |           26.21 |             88.91 |        543.9 |            0.1358  |             0.1892  |           0.1956  |                0.07909 |           0.3168 |                   0.07987 |
| 173 |        11.08  |          14.71 |            70.21 |       372.7 |           0.1006  |            0.05743 |         0.02363  |              0.02583  |          0.1566 |                  0.06669 |      0.2073 |       1.805  |          1.377 |    19.08  |        0.01496  |          0.02121 |       0.01453  |            0.01583  |       0.03082 |               0.004785 |         11.35  |           16.82 |             72.01 |        396.5 |            0.1216  |             0.0824  |           0.03938 |                0.04306 |           0.1902 |                   0.07313 |
| 176 |         9.904 |          18.06 |            64.6  |       302.4 |           0.09699 |            0.1294  |         0.1307   |              0.03716  |          0.1669 |                  0.08116 |      0.4311 |       2.261  |          3.132 |    27.48  |        0.01286  |          0.08808 |       0.1197   |            0.0246   |       0.0388  |               0.01792  |         11.26  |           24.39 |             73.07 |        390.2 |            0.1301  |             0.295   |           0.3486  |                0.0991  |           0.2614 |                   0.1162  |
| 185 |        10.08  |          15.11 |            63.76 |       317.5 |           0.09267 |            0.04695 |         0.001597 |              0.002404 |          0.1703 |                  0.06048 |      0.4245 |       1.268  |          2.68  |    26.43  |        0.01439  |          0.012   |       0.001597 |            0.002404 |       0.02538 |               0.00347  |         11.87  |           21.18 |             75.39 |        437   |            0.1521  |             0.1019  |           0.00692 |                0.01042 |           0.2933 |                   0.07697 |
| 191 |        12.77  |          21.41 |            82.02 |       507.4 |           0.08749 |            0.06601 |         0.03112  |              0.02864  |          0.1694 |                  0.06287 |      0.7311 |       1.748  |          5.118 |    53.65  |        0.004571 |          0.0179  |       0.02176  |            0.01757  |       0.03373 |               0.005875 |         13.75  |           23.5  |             89.04 |        579.5 |            0.09388 |             0.08978 |           0.05186 |                0.04773 |           0.2179 |                   0.06871 |
| 245 |        10.48  |          19.86 |            66.72 |       337.7 |           0.107   |            0.05971 |         0.04831  |              0.0307   |          0.1737 |                  0.0644  |      0.3719 |       2.612  |          2.517 |    23.22  |        0.01604  |          0.01386 |       0.01865  |            0.01133  |       0.03476 |               0.00356  |         11.48  |           29.46 |             73.68 |        402.8 |            0.1515  |             0.1026  |           0.1181  |                0.06736 |           0.2883 |                   0.07748 |
| 266 |        10.6   |          18.95 |            69.28 |       346.4 |           0.09688 |            0.1147  |         0.06387  |              0.02642  |          0.1922 |                  0.06491 |      0.4505 |       1.197  |          3.43  |    27.1   |        0.00747  |          0.03581 |       0.03354  |            0.01365  |       0.03504 |               0.003318 |         11.88  |           22.94 |             78.28 |        424.8 |            0.1213  |             0.2515  |           0.1916  |                0.07926 |           0.294  |                   0.07587 |
| 273 |         9.742 |          15.67 |            61.5  |       289.9 |           0.09037 |            0.04689 |         0.01103  |              0.01407  |          0.2081 |                  0.06312 |      0.2684 |       1.409  |          1.75  |    16.39  |        0.0138   |          0.01067 |       0.008347 |            0.009472 |       0.01798 |               0.004261 |         10.75  |           20.88 |             68.09 |        355.2 |            0.1467  |             0.0937  |           0.04043 |                0.05159 |           0.2841 |                   0.08175 |
| 275 |        11.89  |          17.36 |            76.2  |       435.6 |           0.1225  |            0.0721  |         0.05929  |              0.07404  |          0.2015 |                  0.05875 |      0.6412 |       2.293  |          4.021 |    48.84  |        0.01418  |          0.01489 |       0.01267  |            0.0191   |       0.02678 |               0.003002 |         12.4   |           18.99 |             79.46 |        472.4 |            0.1359  |             0.08368 |           0.07153 |                0.08946 |           0.222  |                   0.06033 |
| 288 |        11.26  |          19.96 |            73.72 |       394.1 |           0.0802  |            0.1181  |         0.09274  |              0.05588  |          0.2595 |                  0.06233 |      0.4866 |       1.905  |          2.877 |    34.68  |        0.01574  |          0.08262 |       0.08099  |            0.03487  |       0.03418 |               0.006517 |         11.86  |           22.33 |             78.27 |        437.6 |            0.1028  |             0.1843  |           0.1546  |                0.09314 |           0.2955 |                   0.07009 |
| 289 |        11.37  |          18.89 |            72.17 |       396   |           0.08713 |            0.05008 |         0.02399  |              0.02173  |          0.2013 |                  0.05955 |      0.2656 |       1.974  |          1.954 |    17.49  |        0.006538 |          0.01395 |       0.01376  |            0.009924 |       0.03416 |               0.002928 |         12.36  |           26.14 |             79.29 |        459.3 |            0.1118  |             0.09708 |           0.07529 |                0.06203 |           0.3267 |                   0.06994 |
| 290 |        14.41  |          19.73 |            96.03 |       651   |           0.08757 |            0.1676  |         0.1362   |              0.06602  |          0.1714 |                  0.07192 |      0.8811 |       1.77   |          4.36  |    77.11  |        0.007762 |          0.1064  |       0.0996   |            0.02771  |       0.04077 |               0.02286  |         15.77  |           22.13 |            101.7  |        767.3 |            0.09983 |             0.2472  |           0.222   |                0.1021  |           0.2272 |                   0.08799 |
| 299 |        10.51  |          23.09 |            66.85 |       334.2 |           0.1015  |            0.06797 |         0.02495  |              0.01875  |          0.1695 |                  0.06556 |      0.2868 |       1.143  |          2.289 |    20.56  |        0.01017  |          0.01443 |       0.01861  |            0.0125   |       0.03464 |               0.001971 |         10.93  |           24.22 |             70.1  |        362.7 |            0.1143  |             0.08614 |           0.04158 |                0.03125 |           0.2227 |                   0.06777 |
| 318 |         9.042 |          18.9  |            60.07 |       244.5 |           0.09968 |            0.1972  |         0.1975   |              0.04908  |          0.233  |                  0.08743 |      0.4653 |       1.911  |          3.769 |    24.2   |        0.009845 |          0.0659  |       0.1027   |            0.02527  |       0.03491 |               0.007877 |         10.06  |           23.4  |             68.62 |        297.1 |            0.1221  |             0.3748  |           0.4609  |                0.1145  |           0.3135 |                   0.1055  |
| 319 |        12.43  |          17    |            78.6  |       477.3 |           0.07557 |            0.03454 |         0.01342  |              0.01699  |          0.1472 |                  0.05561 |      0.3778 |       2.2    |          2.487 |    31.16  |        0.007357 |          0.01079 |       0.009959 |            0.0112   |       0.03433 |               0.002961 |         12.9   |           20.21 |             81.76 |        515.9 |            0.08409 |             0.04712 |           0.02237 |                0.02832 |           0.1901 |                   0.05932 |
| 332 |        11.22  |          19.86 |            71.94 |       387.3 |           0.1054  |            0.06779 |         0.005006 |              0.007583 |          0.194  |                  0.06028 |      0.2976 |       1.966  |          1.959 |    19.62  |        0.01289  |          0.01104 |       0.003297 |            0.004967 |       0.04243 |               0.001963 |         11.98  |           25.78 |             76.91 |        436.1 |            0.1424  |             0.09669 |           0.01335 |                0.02022 |           0.3292 |                   0.06522 |
| 345 |        10.26  |          14.71 |            66.2  |       321.6 |           0.09882 |            0.09159 |         0.03581  |              0.02037  |          0.1633 |                  0.07005 |      0.338  |       2.509  |          2.394 |    19.33  |        0.01736  |          0.04671 |       0.02611  |            0.01296  |       0.03675 |               0.006758 |         10.88  |           19.48 |             70.89 |        357.1 |            0.136   |             0.1636  |           0.07162 |                0.04074 |           0.2434 |                   0.08488 |

##Outliers Cas Malins

In [22]:
# Détection des outliers pour les cas malins
Q1_malignant = M_numeric.quantile(0.25)
Q3_malignant = M_numeric.quantile(0.75)
IQR_malignant = Q3_malignant - Q1_malignant
lower_bound_malignant = Q1_malignant - 1.5 * IQR_malignant
upper_bound_malignant = Q3_malignant + 1.5 * IQR_malignant
outliers_malignant = ((M_numeric < lower_bound_malignant) | (M_numeric > upper_bound_malignant)).any(axis=1)
outliers_df_malignant = M_numeric[outliers_malignant]

In [23]:
print("Outliers dans les cas malins:")
print(outliers_df_malignant.to_markdown())

Outliers dans les cas malins:
|     |   radius_mean |   texture_mean |   perimeter_mean |   area_mean |   smoothness_mean |   compactness_mean |   concavity_mean |   concave points_mean |   symmetry_mean |   fractal_dimension_mean |   radius_se |   texture_se |   perimeter_se |   area_se |   smoothness_se |   compactness_se |   concavity_se |   concave points_se |   symmetry_se |   fractal_dimension_se |   radius_worst |   texture_worst |   perimeter_worst |   area_worst |   smoothness_worst |   compactness_worst |   concavity_worst |   concave points_worst |   symmetry_worst |   fractal_dimension_worst |
|----:|--------------:|---------------:|-----------------:|------------:|------------------:|-------------------:|-----------------:|----------------------:|----------------:|-------------------------:|------------:|-------------:|---------------:|----------:|----------------:|-----------------:|---------------:|--------------------:|--------------:|-----------------------:|---------------:|----------------:|------------------:|-------------:|-------------------:|--------------------:|------------------:|-----------------------:|-----------------:|--------------------------:|
|   0 |         17.99 |          10.38 |           122.8  |      1001   |           0.1184  |            0.2776  |          0.3001  |               0.1471  |          0.2419 |                  0.07871 |      1.095  |       0.9053 |          8.589 |    153.4  |        0.006399 |         0.04904  |        0.05373 |            0.01587  |      0.03003  |               0.006193 |          25.38 |           17.33 |            184.6  |       2019   |            0.1622  |             0.6656  |           0.7119  |                0.2654  |           0.4601 |                   0.1189  |
|   3 |         11.42 |          20.38 |            77.58 |       386.1 |           0.1425  |            0.2839  |          0.2414  |               0.1052  |          0.2597 |                  0.09744 |      0.4956 |       1.156  |          3.445 |     27.23 |        0.00911  |         0.07458  |        0.05661 |            0.01867  |      0.05963  |               0.009208 |          14.91 |           26.5  |             98.87 |        567.7 |            0.2098  |             0.8663  |           0.6869  |                0.2575  |           0.6638 |                   0.173   |
|   9 |         12.46 |          24.04 |            83.97 |       475.9 |           0.1186  |            0.2396  |          0.2273  |               0.08543 |          0.203  |                  0.08243 |      0.2976 |       1.599  |          2.039 |     23.94 |        0.007149 |         0.07217  |        0.07743 |            0.01432  |      0.01789  |               0.01008  |          15.09 |           40.68 |             97.65 |        711.4 |            0.1853  |             1.058   |           1.105   |                0.221   |           0.4366 |                   0.2075  |
|  12 |         19.17 |          24.8  |           132.4  |      1123   |           0.0974  |            0.2458  |          0.2065  |               0.1118  |          0.2397 |                  0.078   |      0.9555 |       3.568  |         11.07  |    116.2  |        0.003139 |         0.08297  |        0.0889  |            0.0409   |      0.04484  |               0.01284  |          20.96 |           29.94 |            151.7  |       1332   |            0.1037  |             0.3903  |           0.3639  |                0.1767  |           0.3176 |                   0.1023  |
|  14 |         13.73 |          22.61 |            93.6  |       578.3 |           0.1131  |            0.2293  |          0.2128  |               0.08025 |          0.2069 |                  0.07682 |      0.2121 |       1.169  |          2.061 |     19.21 |        0.006429 |         0.05936  |        0.05501 |            0.01628  |      0.01961  |               0.008093 |          15.03 |           32.01 |            108.8  |        697.7 |            0.1651  |             0.7725  |           0.6943  |                0.2208  |           0.3596 |                   0.1431  |
|  22 |         15.34 |          14.26 |           102.5  |       704.4 |           0.1073  |            0.2135  |          0.2077  |               0.09756 |          0.2521 |                  0.07032 |      0.4388 |       0.7096 |          3.384 |     44.91 |        0.006789 |         0.05328  |        0.06446 |            0.02252  |      0.03672  |               0.004394 |          18.07 |           19.08 |            125.1  |        980.9 |            0.139   |             0.5954  |           0.6305  |                0.2393  |           0.4667 |                   0.09946 |
|  25 |         17.14 |          16.4  |           116    |       912.7 |           0.1186  |            0.2276  |          0.2229  |               0.1401  |          0.304  |                  0.07413 |      1.046  |       0.976  |          7.276 |    111.4  |        0.008029 |         0.03799  |        0.03732 |            0.02397  |      0.02308  |               0.007444 |          22.25 |           21.4  |            152.4  |       1461   |            0.1545  |             0.3949  |           0.3853  |                0.255   |           0.4066 |                   0.1059  |
|  35 |         16.74 |          21.59 |           110.1  |       869.5 |           0.0961  |            0.1336  |          0.1348  |               0.06018 |          0.1896 |                  0.05656 |      0.4615 |       0.9197 |          3.008 |     45.19 |        0.005776 |         0.02499  |        0.03695 |            0.01195  |      0.02789  |               0.002665 |          20.01 |           29.02 |            133.5  |       1229   |            0.1563  |             0.3835  |           0.5409  |                0.1813  |           0.4863 |                   0.08633 |
|  38 |         14.99 |          25.2  |            95.54 |       698.8 |           0.09387 |            0.05131 |          0.02398 |               0.02899 |          0.1565 |                  0.05504 |      1.214  |       2.188  |          8.077 |    106    |        0.006883 |         0.01094  |        0.01818 |            0.01917  |      0.007882 |               0.001754 |          14.99 |           25.2  |             95.54 |        698.8 |            0.09387 |             0.05131 |           0.02398 |                0.02899 |           0.1565 |                   0.05504 |
|  42 |         19.07 |          24.81 |           128.3  |      1104   |           0.09081 |            0.219   |          0.2107  |               0.09961 |          0.231  |                  0.06343 |      0.9811 |       1.666  |          8.83  |    104.9  |        0.006548 |         0.1006   |        0.09723 |            0.02638  |      0.05333  |               0.007646 |          24.09 |           33.17 |            177.4  |       1651   |            0.1247  |             0.7444  |           0.7242  |                0.2493  |           0.467  |                   0.1038  |
|  62 |         14.25 |          22.15 |            96.42 |       645.7 |           0.1049  |            0.2008  |          0.2135  |               0.08653 |          0.1949 |                  0.07292 |      0.7036 |       1.268  |          5.373 |     60.78 |        0.009407 |         0.07056  |        0.06899 |            0.01848  |      0.017    |               0.006113 |          17.67 |           29.51 |            119.1  |        959.5 |            0.164   |             0.6247  |           0.6922  |                0.1785  |           0.2844 |                   0.1132  |
|  78 |         20.18 |          23.97 |           143.7  |      1245   |           0.1286  |            0.3454  |          0.3754  |               0.1604  |          0.2906 |                  0.08142 |      0.9317 |       1.885  |          8.649 |    116.4  |        0.01038  |         0.06835  |        0.1091  |            0.02593  |      0.07895  |               0.005987 |          23.37 |           31.72 |            170.3  |       1623   |            0.1639  |             0.6164  |           0.7681  |                0.2508  |           0.544  |                   0.09964 |
|  82 |         25.22 |          24.91 |           171.5  |      1878   |           0.1063  |            0.2665  |          0.3339  |               0.1845  |          0.1829 |                  0.06782 |      0.8973 |       1.474  |          7.382 |    120    |        0.008166 |         0.05693  |        0.0573  |            0.0203   |      0.01065  |               0.005893 |          30    |           33.62 |            211.7  |       2562   |            0.1573  |             0.6076  |           0.6476  |                0.2867  |           0.2355 |                   0.1051  |
|  83 |         19.1  |          26.29 |           129.1  |      1132   |           0.1215  |            0.1791  |          0.1937  |               0.1469  |          0.1634 |                  0.07224 |      0.519  |       2.91   |          5.801 |     67.1  |        0.007545 |         0.0605   |        0.02134 |            0.01843  |      0.03056  |               0.01039  |          20.33 |           32.72 |            141.3  |       1298   |            0.1392  |             0.2817  |           0.2432  |                0.1841  |           0.2311 |                   0.09203 |
| 105 |         13.11 |          15.56 |            87.21 |       530.2 |           0.1398  |            0.1765  |          0.2071  |               0.09601 |          0.1925 |                  0.07692 |      0.3908 |       0.9238 |          2.41  |     34.66 |        0.007162 |         0.02912  |        0.05473 |            0.01388  |      0.01547  |               0.007098 |          16.31 |           22.4  |            106.4  |        827.2 |            0.1862  |             0.4099  |           0.6376  |                0.1986  |           0.3147 |                   0.1405  |
| 108 |         22.27 |          19.67 |           152.8  |      1509   |           0.1326  |            0.2768  |          0.4264  |               0.1823  |          0.2556 |                  0.07039 |      1.215  |       1.545  |         10.05  |    170    |        0.006515 |         0.08668  |        0.104   |            0.0248   |      0.03112  |               0.005037 |          28.4  |           28.01 |            206.8  |       2360   |            0.1701  |             0.6997  |           0.9608  |                0.291   |           0.4055 |                   0.09789 |
| 119 |         17.95 |          20.01 |           114.2  |       982   |           0.08402 |            0.06722 |          0.07293 |               0.05596 |          0.2129 |                  0.05025 |      0.5506 |       1.214  |          3.357 |     54.04 |        0.004024 |         0.008422 |        0.02291 |            0.009863 |      0.05014  |               0.001902 |          20.58 |           27.83 |            129.2  |       1261   |            0.1072  |             0.1202  |           0.2249  |                0.1185  |           0.4882 |                   0.06111 |
| 122 |         24.25 |          20.2  |           166.2  |      1761   |           0.1447  |            0.2867  |          0.4268  |               0.2012  |          0.2655 |                  0.06877 |      1.509  |       3.12   |          9.807 |    233    |        0.02333  |         0.09806  |        0.1278  |            0.01822  |      0.04547  |               0.009875 |          26.02 |           23.99 |            180.9  |       2073   |            0.1696  |             0.4244  |           0.5803  |                0.2248  |           0.3222 |                   0.08009 |
| 138 |         14.95 |          17.57 |            96.85 |       678.1 |           0.1167  |            0.1305  |          0.1539  |               0.08624 |          0.1957 |                  0.06216 |      1.296  |       1.452  |          8.419 |    101.9  |        0.01     |         0.0348   |        0.06577 |            0.02801  |      0.05168  |               0.002887 |          18.55 |           21.43 |            121.4  |        971.4 |            0.1411  |             0.2164  |           0.3355  |                0.1667  |           0.3414 |                   0.07147 |
| 146 |         11.8  |          16.58 |            78.99 |       432   |           0.1091  |            0.17    |          0.1659  |               0.07415 |          0.2678 |                  0.07371 |      0.3197 |       1.426  |          2.281 |     24.72 |        0.005427 |         0.03633  |        0.04649 |            0.01843  |      0.05628  |               0.004635 |          13.74 |           26.38 |             91.93 |        591.7 |            0.1385  |             0.4092  |           0.4504  |                0.1865  |           0.5774 |                   0.103   |
| 161 |         19.19 |          15.94 |           126.3  |      1157   |           0.08694 |            0.1185  |          0.1193  |               0.09667 |          0.1741 |                  0.05176 |      1      |       0.6336 |          6.971 |    119.3  |        0.009406 |         0.03055  |        0.04344 |            0.02794  |      0.03156  |               0.003362 |          22.03 |           17.81 |            146.6  |       1495   |            0.1124  |             0.2016  |           0.2264  |                0.1777  |           0.2443 |                   0.06251 |
| 172 |         15.46 |          11.89 |           102.5  |       736.9 |           0.1257  |            0.1555  |          0.2032  |               0.1097  |          0.1966 |                  0.07069 |      0.4209 |       0.6583 |          2.805 |     44.64 |        0.005393 |         0.02321  |        0.04303 |            0.0132   |      0.01792  |               0.004168 |          18.79 |           17.04 |            125    |       1102   |            0.1531  |             0.3583  |           0.583   |                0.1827  |           0.3216 |                   0.101   |
| 180 |         27.22 |          21.87 |           182.1  |      2250   |           0.1094  |            0.1914  |          0.2871  |               0.1878  |          0.18   |                  0.0577  |      0.8361 |       1.481  |          5.82  |    128.7  |        0.004631 |         0.02537  |        0.03109 |            0.01241  |      0.01575  |               0.002747 |          33.12 |           32.85 |            220.8  |       3216   |            0.1472  |             0.4034  |           0.534   |                0.2688  |           0.2856 |                   0.08082 |
| 181 |         21.09 |          26.57 |           142.7  |      1311   |           0.1141  |            0.2832  |          0.2487  |               0.1496  |          0.2395 |                  0.07398 |      0.6298 |       0.7629 |          4.414 |     81.46 |        0.004253 |         0.04759  |        0.03872 |            0.01567  |      0.01798  |               0.005295 |          26.68 |           33.48 |            176.5  |       2089   |            0.1491  |             0.7584  |           0.678   |                0.2903  |           0.4098 |                   0.1284  |
| 190 |         14.22 |          23.12 |            94.37 |       609.9 |           0.1075  |            0.2413  |          0.1981  |               0.06618 |          0.2384 |                  0.07542 |      0.286  |       2.11   |          2.112 |     31.72 |        0.00797  |         0.1354   |        0.1166  |            0.01666  |      0.05113  |               0.01172  |          15.74 |           37.18 |            106.4  |        762.4 |            0.1533  |             0.9327  |           0.8488  |                0.1772  |           0.5166 |                   0.1446  |
| 196 |         13.77 |          22.29 |            90.63 |       588.9 |           0.12    |            0.1267  |          0.1385  |               0.06526 |          0.1834 |                  0.06877 |      0.6191 |       2.112  |          4.906 |     49.7  |        0.0138   |         0.03348  |        0.04665 |            0.0206   |      0.02689  |               0.004306 |          16.39 |           34.01 |            111.6  |        806.9 |            0.1737  |             0.3122  |           0.3809  |                0.1673  |           0.308  |                   0.09333 |
| 197 |         18.08 |          21.84 |           117.4  |      1024   |           0.07371 |            0.08642 |          0.1103  |               0.05778 |          0.177  |                  0.0534  |      0.6362 |       1.305  |          4.312 |     76.36 |        0.00553  |         0.05296  |        0.0611  |            0.01444  |      0.0214   |               0.005036 |          19.76 |           24.7  |            129.1  |       1228   |            0.08822 |             0.1963  |           0.2535  |                0.09181 |           0.2369 |                   0.06558 |
| 202 |         23.29 |          26.67 |           158.9  |      1685   |           0.1141  |            0.2084  |          0.3523  |               0.162   |          0.22   |                  0.06229 |      0.5539 |       1.56   |          4.667 |     83.16 |        0.009327 |         0.05121  |        0.08958 |            0.02465  |      0.02175  |               0.005195 |          25.12 |           32.68 |            177    |       1986   |            0.1536  |             0.4167  |           0.7892  |                0.2733  |           0.3198 |                   0.08762 |
| 203 |         13.81 |          23.75 |            91.56 |       597.8 |           0.1323  |            0.1768  |          0.1558  |               0.09176 |          0.2251 |                  0.07421 |      0.5648 |       1.93   |          3.909 |     52.72 |        0.008824 |         0.03108  |        0.03112 |            0.01291  |      0.01998  |               0.004506 |          19.2  |           41.85 |            128.5  |       1153   |            0.2226  |             0.5209  |           0.4646  |                0.2013  |           0.4432 |                   0.1086  |
| 210 |         20.58 |          22.14 |           134.7  |      1290   |           0.0909  |            0.1348  |          0.164   |               0.09561 |          0.1765 |                  0.05024 |      0.8601 |       1.48   |          7.029 |    111.7  |        0.008124 |         0.03611  |        0.05489 |            0.02765  |      0.03176  |               0.002365 |          23.24 |           27.84 |            158.3  |       1656   |            0.1178  |             0.292   |           0.3861  |                0.192   |           0.2909 |                   0.05865 |
| 212 |         28.11 |          18.47 |           188.5  |      2499   |           0.1142  |            0.1516  |          0.3201  |               0.1595  |          0.1648 |                  0.05525 |      2.873  |       1.476  |         21.98  |    525.6  |        0.01345  |         0.02772  |        0.06389 |            0.01407  |      0.04783  |               0.004476 |          28.11 |           18.47 |            188.5  |       2499   |            0.1142  |             0.1516  |           0.3201  |                0.1595  |           0.1648 |                   0.05525 |
| 213 |         17.42 |          25.56 |           114.5  |       948   |           0.1006  |            0.1146  |          0.1682  |               0.06597 |          0.1308 |                  0.05866 |      0.5296 |       1.667  |          3.767 |     58.53 |        0.03113  |         0.08555  |        0.1438  |            0.03927  |      0.02175  |               0.01256  |          18.07 |           28.07 |            120.4  |       1021   |            0.1243  |             0.1793  |           0.2803  |                0.1099  |           0.1603 |                   0.06818 |

##Total Outliers

In [24]:
out_benign = pd.DataFrame(outliers_df_benign.nunique())
out_benign.rename(columns = {0: "Outliers B"}, inplace = True)

out_malign = pd.DataFrame(outliers_df_malignant.nunique())
out_malign.rename(columns = {0: "Outliers M"}, inplace = True)

In [25]:
df_outliers = pd.concat([out_benign, out_malign], axis = 1)
df_outliers

                         Outliers B  Outliers M
radius_mean                      49          61
texture_mean                     49          61
perimeter_mean                   50          60
area_mean                        51          61
smoothness_mean                  51          58
compactness_mean                 51          60
concavity_mean                   51          61
concave points_mean              51          60
symmetry_mean                    51          60
fractal_dimension_mean           51          60
radius_se                        50          61
texture_se                       51          61
perimeter_se                     51          60
area_se                          50          60
smoothness_se                    49          61
compactness_se                   51          61
concavity_se                     50          61
concave points_se                50          60
symmetry_se                      50          59
fractal_dimension_se             51          61
radius_worst                     48          59
texture_worst                    50          61
perimeter_worst                  51          59
area_worst                       51          61
smoothness_worst                 48          61
compactness_worst                49          61
concavity_worst                  51          61
concave points_worst             51          60
symmetry_worst                   51          61
fractal_dimension_worst          51          61

In [26]:
df_CduS.shape

(556, 31)

In [27]:
round((len(outliers_df_benign) / len(df_CduS)) * 100, 2)

9.17

In [28]:
round((len(outliers_df_malignant) / len(df_CduS)) * 100, 2)

10.97

Le client nous indique qu'il ne faut pas considérer ces valeurs extrêmes comme des outliers et donc ces valeurs ne nécessitent pas de traitement particulier

In [29]:
df_CduS.to_csv("/content/drive/MyDrive/PARIS 0224 - Data Analyst/Projets/projet3/Vital Stats - Hadi, Sylvain, Henri, Khadija, Erwan/Cancer du Sein/df_CduS.csv", index = False)